<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.11.0-beta.3" />
    <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="3.1.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.6.0" />
  </ItemGroup>
    <ItemGroup>
    <ProjectReference Include="..\SISPAE.Common\SISPAE.Common.csproj" />
    <ProjectReference Include="..\SISPAE.DataAccess\SISPAE.DataAccess.csproj" />
    <ProjectReference Include="..\SISPAE.Model\SISPAE.Model.csproj" />
  </ItemGroup>


</Project>
